DATASET:
  root_dataset: "/scratch0/chenjin/DeepGlob/"
  list_train: "./data/DeepGlob/labd_train_list_803_shuff_455.odgt"
  list_val: "./data/DeepGlob/labd_train_list_803_shuff_207.odgt"
  num_class: 7
  imgSizes: (2448, )
  imgMaxSize: 2448
  padding_constant: 4
  segm_downsampling_rate: 4
  random_flip: "Flip"

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "c1"
  fc_dim: 720
  foveation: True
  hard_fov: False
  hard_grad: "st_inv"
  hard_fov_pred: False
  fov_padding: False
  deep_fov: ""
  in_dim: 3
  fov_map_scale: 24
  patch_bank: [1000, 1360, 1720, 2080, 2448]
  one_hot_patch: []
  pre_cropped: False
  cropped_lists: []

TRAIN:
  auto_batch: 'manual'
  batch_size_per_gpu: 1
  fov_location_step: 1
  auto_fov_location_step: False
  sync_location: 'mean_mbs'
  mini_batch_size: 1
  num_epoch: 200
  start_epoch: 0
  epoch_iters: 1
  optim: "adam"
  lr_encoder: 2e-5
  lr_decoder: 2e-5
  lr_foveater: 2e-5
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  weight_decay_fov: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 4
  disp_iter: 20
  seed: 304
  save_checkpoint: True

VAL:
  visualize: False
  checkpoint: "epoch_last.pth"
  hard_max_fov: False
  max_score: False
  central_crop: False

TEST:
  checkpoint: "epoch_50.pth"
  result: "./"

DIR: "ckpt/Foveated_Seg/cityscape_train1_val1"
